# Learn more: https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
      - stable
    exclude:
      - refs/tags/v*
pr:
  branches:
    include:
      - master
      - stable

jobs:
  - job: Windows
    timeoutInMinutes: 120

    pool:
      vmImage: 'windows-latest'
    strategy:
      matrix:
        x64:
          DC: ldc
          DVersion: '1.21.0'
          arch: x64
    steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'
      - powershell: function SetUpDCompiler
        {
            if($env:DC -eq "dmd"){
              if($env:arch -eq "x86"){
                $env:DConf = "m32";
              }
              elseif($env:arch -eq "x64"){
                $env:DConf = "m64";
              }
              echo "downloading ...";
              $env:toolchain = "msvc";
              $version = $env:DVersion;
              Invoke-WebRequest "http://downloads.dlang.org/releases/2.x/$($version)/dmd.$($version).windows.7z" -OutFile "c:\dmd.7z";
              echo "finished.";
              pushd c:\\;
              7z x dmd.7z > $null;
              popd;
            }
            elseif($env:DC -eq "ldc"){
              echo "downloading ...";
              if($env:arch -eq "x86"){
                $env:DConf = "m32";
              }
              elseif($env:arch -eq "x64"){
                $env:DConf = "m64";
              }
              $env:toolchain = "msvc";
              $version = $env:DVersion;
              Invoke-WebRequest "https://github.com/ldc-developers/ldc/releases/download/v$($version)/ldc2-$($version)-windows-x64.7z" -OutFile "c:\ldc.7z";
              echo "finished.";
              pushd c:\\;
              7z x ldc.7z > $null;
              popd;
            }
        }
      - script: |
          echo dummy build script - dont remove me
        displayName: build_script
